services:
  db:
    image: postgres:17.5-alpine
    container_name: postgres-dev
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: dev-password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  cache: 
    image: redis:8.0-alpine
    container_name: redis-dev
    command:
      - redis-server
      - --maxmemory 128mb
      - --maxmemory-policy allkeys-lfu
      - --lfu-log-factor 10   # default value
      - --lfu-decay-time 1    # default value
      # - --activedefrag yes
      - --save ""
      - --appendonly no
      - --loglevel notice
      - --logfile ""
    restart: unless-stopped
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:4.1-management
    container_name: rabbitmq-dev
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    # environment:
    #   RABBITMQ_DEFAULT_USER: guest
    #   RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres_data: